### ISSUE TITLE
Enable batch result fetching for large numbers of results

### ISSUE THREAD

**Issue by ChristelKrueger** [ewels/sra-explorer#1]
Hi Phil,

We would like to get hold of some single cell RNA Seq data with the accession number ERP005988. It works fine when you specify a limit of 500, but fails above that (e.g. 2000 or 800). Any clues?

Cheers, Christel

**Comment by ewels** [comment]
Hi @ChristelKrueger,

I'm afraid that there are some clues and they're not particularly helpful - if you copy and paste the URL into your browser you get this:
```
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=sra&retmode=json&query_key=1&WebEnv=NCID_1_537776479_130.14.18.34_9001_1492681119_52949731_0MetA0_S_MegaStore_F_1&retstart=0&retmax=2000
```
```json
{
  "header": {
    "type": "esummary",
    "version": "0.3"
  },
  "error": "Too many UIDs in request. Maximum number of UIDs is 500 for JSON format output."
}
```

Notice that there are a couple of parameters in the URL which are important here: `retstart=0&retmax=2000`

So the way to get around this is to do batches of 500, increasing the starting point each time. For example:

1. `retstart=0&retmax=500`
2. `retstart=500&retmax=500`
3. `retstart=1000&retmax=500`
4. _..and so on_

The down side is that this sra-explorer tool doesn't (yet) support such paging of batch results.

You're welcome to fork the repo and implement the code yourself, and then submit a pull-request back!

Phil

**Comment by ewels** [comment]
It [looks like](https://github.com/ewels/sra-explorer/blob/gh-pages/index.html#L309-L311) I had this in mind when I wrote the code, but never finished implementing it. There is already a `retstart` variable in the code:

```javascript
var retstart = 0;
var retmax = $scope.maxResults;
var resultsURL = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=sra&retmode=json&query_key='+querykey+'&WebEnv='+webenv+'&retstart='+retstart+'&retmax='+retmax;
```

So the quick and hacky fix is to add another input box to allow the user to specify a `retmax` value. Then hook this up to the AngularJS model and access it using `$scope.retstart;`

Not as nice as enabling proper batch fetching in a single request, but it'd be quite a bit easier to write.

Phil

**Comment by ewels** [comment]
Hi @ChristelKrueger,

I've just done this for you in b8343157b6b4913b8079365dcc41c43f63e2b1a2. Should appear online any moment now.

Let me know how you get on!

Phil
