### ISSUE TITLE
Stuck at Loading?

### ISSUE THREAD

**Issue by cpgme** [ewels/sra-explorer#12]
Great tool. I really like it.

It seems it stopped working when I want to use it today.
It's stuck at the loading process even with the example IDs.

I guess it might be related to the changes made at SRA Run Selector:
2019-08-19: SRA data is now available in the cloud.

**Comment by cpgme** [comment]
It works again. Interesting.

**Comment by ewels** [comment]
Mysterious! Maybe just a blip in the SRA API service. If it fails again in the future you can have a look in your web browser developer console ([instructions](https://www.lifewire.com/web-browser-developer-tools-3988965)) and see what errors are logged.

Phil

**Comment by cpgme** [comment]
Thanks for the quick response.
I did try different browsers, all suck in loading.
But when I reload the webpage, I saw a flash of lines of info which resembles the lists I would expect.
