### ISSUE TITLE
No response for GEO accession

### ISSUE THREAD

**Issue by hmkim** [ewels/sra-explorer#16]
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE70138

For this accession, sra-explorer is not working for me.
(GSE70138[All Fields])

Could you check for this accession, please?

**Comment by ewels** [comment]
Hi @hmkim,

This accession doesn't appear to be part of the SRA - I don't get any hits on the main SRA website either: https://www.ncbi.nlm.nih.gov/sra/?term=GSE70138

Looking at the GEO link you sent, it appears that this project was done using a fluorescence system and not DNA sequencing.

Phil

**Comment by hmkim** [comment]
Hi @ewels.
I got it. 
Thank you for your reply.
