### ISSUE TITLE
Accessions with SRA download but no fastq download

### ISSUE THREAD

**Issue by vpeddu** [ewels/sra-explorer#21]
Found a few accessions like SRR11945694 that have a valid SRA download command but the fastq download command hangs at loading. Is this because fastqs aren't readily available?

**Comment by ewels** [comment]
Yup, if you look at the EBI API results for this accession you can see that there are no FastQ fiels available: https://www.ebi.ac.uk/ena/data/warehouse/filereport?result=read_run&fields=fastq_ftp&accession=SRR11945694

```
fastq_ftp
```

You can also see that the FastQ table cells are blank on the web page: https://www.ebi.ac.uk/ena/data/view/SRR11945694

I have an issue open to warn when this is the case (https://github.com/ewels/sra-explorer/issues/7), but I haven't yet found time to implement it sorry.

Phil
