### ISSUE TITLE
sra-explorer can't find some links for download

### ISSUE THREAD

**Issue by FerallOut** [ewels/sra-explorer#22]
![Screenshot from 2020-07-23 07-01-06](https://user-images.githubusercontent.com/49016186/88253694-16aefb00-ccb3-11ea-9c2a-49e308136277.png)

 I have found this problem only with the links from this experiment. No matter how long I wait, the bash file doesn't get populated with the links I need to download. I don't know where the issue could be

All the best and thank you for this great tool :) !

**Comment by FerallOut** [comment]
Ah, sorry, I have just looked through the issues raised before and I now understand that maybe the fastq files might not exist for some projects. I will download the sra and then convert them. Sorry for not seeing this before!

All the best!

**Comment by ewels** [comment]
No problem! Apologies for not yet implementing a more user-friendly check for this already.. 🙄
