### ISSUE TITLE
can't acess GSEXXX

### ISSUE THREAD

**Issue by HouyuZhang** [ewels/sra-explorer#23]
Hi, ewels,
Thanks for this convenient and powerful tool for accessing NGS data. 
However, recently I can't access the GEO database using GSE number, for example, GSE121123 here returns nothing.
![image](https://user-images.githubusercontent.com/16659952/89263001-16bfdb00-d663-11ea-8c50-ca2a0b1e6d0f.png)
Of, note, the demo you offered under the search box all works fine:
![image](https://user-images.githubusercontent.com/16659952/89263125-42db5c00-d663-11ea-977f-05baa9fe1cf6.png)
Could you please give some suggestions on this situation. Thanks in advance!

**Comment by HouyuZhang** [comment]
The issue occurred before and this is due to GEO set up.
I found using GSM1 OR GSM2 OR ... GSM20 can also help me batch download data :)

**Comment by ewels** [comment]
Yes this tool doesn't know about GEO so it requires datasets to be correctly labelled in the SRA.

Maybe try with https://pypi.org/project/pysradb/
