### ISSUE TITLE
Multiple SRA accession

### ISSUE THREAD

**Issue by ZarulHanifah** [ewels/sra-explorer#30]
Hello,

Is it possible to enter multiple SRA accessions with SRA explorer. I have a list, and its just tedious to input one by one... and there is no commandline alternative that I know of on my head

**Comment by ZarulHanifah** [comment]
Figured it out, just add OR in between accessions, sorry

**Comment by ewels** [comment]
Glad you figured it out! If you’re looking for a command line tool, check out https://github.com/saketkc/pysradb

Phil
