### ISSUE TITLE
SRA explorer not generating Aspera FASTQ download scripts

### ISSUE THREAD

**Issue by ASethiProjects** [ewels/sra-explorer#31]
See title

**Comment by ewels** [comment]
Title isn't sufficient sorry. Works fine for me: 

<img src ="https://user-images.githubusercontent.com/465550/112267951-85938800-8c76-11eb-9a95-fb23d5f24edc.png" height=800>

What accession? Which datasets? Not working how?

**Comment by ASethiProjects** [comment]
That library works for me. However, this one doesn't: 
SRR12802840

**Comment by ASethiProjects** [comment]
Download works now.  I think the recently uploaded libraries had not synced to ENA when I posted the original thread, but were made available in the subsequent days.

**Comment by ewels** [comment]
Ok, great that it fixed itself! Thanks for letting me know. Planned is https://github.com/ewels/sra-explorer/issues/7 which when implemented should warn that the files are not found on the ENA at least, to give you more of a hint.
