### ISSUE TITLE
How download data for more than 500 sample 

### ISSUE THREAD

**Issue by Hemantcnaik** [ewels/sra-explorer#35]
Hello, Thank you very usefull tool 

Can you please suggest how to use sra-explorer for more than 500 datasets 

please help me

**Comment by ewels** [comment]
Please use a command tool for this. For example:

* [nf-core/fetchngs](https://nf-co.re/fetchngs)
* [pysradb](https://github.com/saketkc/pysradb)
* [fetchfastq](https://github.com/pachterlab/ffq)

I should add note of these tools to the readme / web page...

**Comment by ewels** [comment]
Readme updated in 0df349600e5444c0dee07654b70add4eec72ca77 and `index.html` in 7807ca95a07f3d935a335ec7fe913cd713e5ecbc
