### ISSUE TITLE
Bash code for downloading fastq files not working anymore

### ISSUE THREAD

**Issue by niekwit** [ewels/sra-explorer#36]
Thank you for making this wonderful tool! I have tried to download fastq files from SRP162175 using the bash code that is generated by SRA-explorer.
This is one example:
```
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR787/004/SRR7879424/SRR7879424_1.fastq.gz -o SRR7879424_GSM3396116_WT_repeat1_RS154_Homo_sapiens_RNA-Seq_1.fastq.gz
```
But instead of the download starting, I get the following error:
```
curl: (9) Server denied you to change to the given directory
```
This suggests that the directory does not exist? When I connect to the EBI ftp server with FileZilla, I cannot see a `vol1` directory. Do you know if the data has moved, and if so, are you able to update the bash command (as they are very handy!).

Thank you very much,

Niek

**Comment by genomax** [comment]
Replace `ftp` with `http` and the link will work.

**Comment by ewels** [comment]
Hi Niek,

I just tried the command you pasted and it worked fine for me. Can you try again? It could have just been a hiccup?

If you're getting this all the time, could you try some other datasets? To check if it's specific to new / old / certain data. Sometimes very new datasets especially take some time to percolate through the system and can cause issues. It looks like this sample is from 2019 though, so I doubt that's it.

@genomax could you elaborate on your suggestion? I don't think I've ever had issues with `curl` supporting ftp versus http..

Phil

**Comment by niekwit** [comment]
Hi Phil,

I have tried the same code again, and now it does work. It was probably a hiccup that lasted for a few days. Thanks!

Best wishes,

Niek

**Comment by ewels** [comment]
The best kind of bug! 🎉 

Thanks for letting me know 😃
