### ISSUE TITLE
compatibilty with bcbio

### ISSUE THREAD

**Issue by lpantano** [ewels/sra-explorer#4]
Hi!

any chance to create a bcbio project file like this as another option:

```
samplename,description
ENA_ftp_url,clean_name
```

That would be awesome!!!!!

Only if fastq are available.

Pretty please :)

Thanks for this!

**Comment by ewels** [comment]
Yeah, shouldn't be too tricky 😄 Formatting the data output is the easy (and fun!) bit...

**Comment by ewels** [comment]
Done! 🎉

**Comment by lpantano** [comment]
tuhuuuu tou are fast! thanks!
