### ISSUE TITLE
Unable to download file

### ISSUE THREAD

**Issue by jestlin15** [ewels/sra-explorer#40]
Hi, I am trying to download the file with the following code I copied from SRA explorer:

```bash
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR100/047/SRR10044447/SRR10044447_2.fastq.gz -o SRR10044447_GSM4054771_SN_PD_4_Homo_sapiens_RNA-Seq_2.fastq.gz
```

however it keeps getting timed out even when I have tried different wifi and lan connection. I have also tried wget instead of curl.It seems to be stuck after reaching 59% every time. Could you hep me please?

**Comment by ewels** [comment]
This is to with the ENA - the sra explorer just fetches the links, it doesn't have anything to do with the download. You'll need to contact them for help sorry.
