### ISSUE TITLE
Mismatch with queried BioProject ID connecting to a different BioProject/Accession

### ISSUE THREAD

**Issue by TromboneEngineer** [ewels/sra-explorer#41]
Searched: PRJEB52272 (see: https://www.ncbi.nlm.nih.gov/bioproject/PRJEB52272)
Returned: [ERR9976022](https://www.ncbi.nlm.nih.gov/sra/?term=ERR9976022)

The issue is that these accessions are not supposed to be connected. It seems that the project I queried is still not publicly available, but I wanted to inform SRA Explorer folks that this mismatch is linked by this tool.

**Comment by ewels** [comment]
It looks like the SRA returns the same: https://www.ncbi.nlm.nih.gov/sra/?term=PRJEB52272

SRA-explorer is just a front-end. I can't do anything about incorrect data returned from the SRA I'm afraid. This needs to be reported to the SRA directly.
