### ISSUE TITLE
Doesn't recognise GSE77453

### ISSUE THREAD

**Issue by s-andrews** [ewels/sra-explorer#6]
Haven't looked into this at all, but putting GSE77453 into the search gives nothing back despite it being a valid ID.  If you take the SRA number for the same study (SRP069154) then that works just fine.

It's probably something trivial - or just the NCBI API being broken again...

**Comment by s-andrews** [comment]
Hmm.  This URL

```
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=sra&usehistory=y&retmode=json&term=GSE77453
```

Gives a big pile of nothing.  Looks like it might be an NCBI thing.

**Comment by ewels** [comment]
¯\\_(ツ)_/¯

**Comment by s-andrews** [comment]
I see you fixed your arm quoting error :-)

**Comment by ewels** [comment]
I did!   &nbsp;  &nbsp;     \\( ﾟヮﾟ)/

Thanks for checking.. 😅
